pipeline:
  identifier: Build_hashinyc_jhttp_1746721210538
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: CI_Pipeline
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1746652796717
        repoName: hashinyc/jhttp
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: build_java_app
                  name: Build Java App
                  type: Run
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
                  timeout: 10m
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerHub
                    repo: baiyun/jhttp
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
